

services:
  db:
    image: postgres:15-alpine
    container_name: leetcoderanked-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres1}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-leetranked}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: